name: 'kubeapply-action'
description: 'Runs kubeapply ihttps://github.com/segmentio/kubeapply'
branding:
  icon: 'command'
  color: 'green'
inputs:
  command:
    description: 'kubeapply command to run'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/elinesterov/kubeapply-action:latest'
  args:
    - ${{ inputs.command }}
