name: Test kubeapply action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test kubeapply action works
        uses: elinesterov/kubeapply-action@main
        with:
          command: kubeapply expand tests/test-data/clusters/local.yaml
